##MongoDB document databases  
## Pull the mongo:4.4 image
FROM mongo:4.4

## The maintainer name and email
LABEL Maintainer Mohamed Ziada <mohamed@ibiidi.com>

#COPY mongod.conf /etc/mongo/mongod.conf
# Expose the default port
EXPOSE 27017